# Generated by Django 5.1.1 on 2024-12-24 04:19

import datetime
import django.db.models.deletion
import food_fusion_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Lahore', 'Lahore'), ('Hyderabad', 'Hyderabad')], max_length=100)),
                ('town', models.CharField(choices=[('Fazaltown', 'Fazaltown'), ('Faisaltown', 'Faisaltown'), ('Shahkhalid', 'Shahkhalid'), ('GulzareQaid', 'Gulzareqaid'), ('AirportSociety', 'Airportsociety'), ('Gulraiz', 'Gulraiz'), ('Goritown', 'Goritown'), ('Koraltown', 'Koraltown')], max_length=50)),
                ('mainstreet', models.CharField(max_length=20)),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=11, validators=[food_fusion_api.validators.validator_contact])),
                ('type', models.CharField(choices=[('barBQ', 'Barbq'), ('fastfood', 'Fastfood'), ('barBQfastfood', 'Barbqfastfood')], default='None', max_length=100)),
                ('open_time', models.TimeField(default=datetime.time(9, 0))),
                ('closs_time', models.TimeField(default=datetime.time(23, 59))),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.address')),
            ],
        ),
    ]
