# Generated by Django 5.1.1 on 2024-12-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_address_remove_restaurant_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurant.restaurant'),
        ),
    ]
