# Generated by Django 5.1.1 on 2024-12-28 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_address_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Branch1', 'Branch1'), ('Branch2', 'Branch2'), ('Branch3', 'Branch3'), ('Branch4', 'Branch4'), ('Branch5', 'Branch5'), ('Branch6', 'Branch6'), ('Branch7', 'Branch7'), ('Branch8', 'Branch8'), ('Branch9', 'Branch9'), ('Branch10', 'Branch10')], max_length=20)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='restaurant.address')),
            ],
        ),
    ]
