# Generated by Django 5.1.1 on 2024-12-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_branch_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closs_time',
            new_name='close_time',
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
