# Generated by Django 5.1.1 on 2025-01-02 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_address_id_branch_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_lane1', models.CharField(max_length=100)),
                ('address_lane2', models.CharField(max_length=100, null=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('city', models.CharField(choices=[('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Lahore', 'Lahore'), ('Hyderabad', 'Hyderabad'), ('Multan', 'Multan')], max_length=100)),
                ('town', models.CharField(choices=[('Fazaltown', 'Fazaltown'), ('Faisaltown', 'Faisaltown'), ('Shahkhalid', 'Shahkhalid'), ('GulzareQaid', 'Gulzareqaid'), ('AirportSociety', 'Airportsociety'), ('Gulraiz', 'Gulraiz'), ('Goritown', 'Goritown'), ('Koraltown', 'Koraltown')], max_length=50)),
                ('mainstreet', models.CharField(max_length=20)),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 0, 51, 42, 366972))),
            ],
        ),
    ]
