# Generated by Django 5.1.1 on 2025-01-02 20:03

from django.db import migrations

def migrate_address_to_addresses(apps,schema_editor):
    Address=apps.get_model('restaurant','Address')
    Addresses=apps.get_model('restaurant','Addresses')
    for address in Address.objects.all():
        Addresses.objects.create(
            address_lane1=address.mainstreet,
            entity_type='branch',
            entity_id=address.restaurant.id,
            city=address.city,
            town=address.town,
            mainstreet=address.mainstreet
        )
    

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_addresses'),
    ]

    operations = [
        migrations.RunPython(migrate_address_to_addresses)
    ]
