# Generated by Django 5.1.1 on 2025-01-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20250103_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='mainstreet',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='plot',
        ),
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='addresses',
            name='postal_code',
            field=models.CharField(default='4646', max_length=10),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 14, 56, 9, 85403)),
        ),
    ]
