# Generated by Django 5.1.1 on 2025-01-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_restaurant_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address_lane2',
            field=models.CharField(help_text='Optional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
