# Generated by Django 5.1.1 on 2025-01-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('orders', '0010_alter_orderitems_delievery_address'),
        ('restaurant', '0015_alter_branch_address_delete_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
    ]
