# Generated by Django 5.1.1 on 2024-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='enter the rating between 0.0 and 5.0', max_digits=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.CharField(choices=[('barBQ', 'Barbq'), ('fastfood', 'Fastfood'), ('chiniesfood', 'Chiniesfood'), ('pakistanifood', 'Pakistanifood'), ('italianfood', 'Italianfood')], default='None', max_length=50),
        ),
    ]
