# Generated by Django 5.1.1 on 2025-02-03 11:15

import django.db.models.deletion
from django.db import migrations, models

def create_branch_fk_for_products(apps,schema_editor):
    Products=apps.get_model('products','Products')
    Branch=apps.get_model('restaurant','Branch')
    default_branch=Branch.objects.filter(id=24).first()
    if default_branch:
          Products.objects.filter(restaurant__isnull=False).update(restaurant=default_branch)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_restaurant'),
        ('restaurant', '0015_alter_branch_address_delete_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurant.branch'),
        ),
    ]
