# Generated by Django 5.1.1 on 2025-01-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='res_id',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
    ]
