# Generated by Django 5.1.1 on 2025-01-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_cartitem_rename_ordercart_orderitems_checkout_and_more'),
        ('products', '0004_alter_products_restaurant'),
        ('restaurant', '0014_addresses_updated_at_alter_addresses_address_lane2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercart', to='orders.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercart', to='products.products'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delievery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.addresses'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.products'),
        ),
    ]
