# Generated by Django 5.1.1 on 2025-01-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cartitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cartitem'),
        ),
    ]
