# Generated by Django 5.1.1 on 2025-01-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_checkout_customer_remove_checkout_restaurant_and_more'),
        ('restaurant', '0014_addresses_updated_at_alter_addresses_address_lane2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delievery_address',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='delievery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.addresses'),
        ),
    ]
