# Generated by Django 5.1.1 on 2025-01-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_checkout_delievery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='branch',
        ),
    ]
