# Generated by Django 5.1.1 on 2025-01-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('orders', '0009_remove_checkout_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='delievery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='address.addresses'),
        ),
    ]
