# Generated by Django 5.1.1 on 2025-01-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_addresses_address'),
        ('orders', '0010_alter_orderitems_delievery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='cartitems',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='delievery_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='address.address'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cartitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cartitem'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='Confermed', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.checkout'),
        ),
    ]
