# Generated by Django 5.1.1 on 2025-01-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_checkout_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='orders.cart'),
        ),
    ]
