# Generated by Django 5.1.1 on 2025-02-01 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_checkout_cartitems_checkout_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
