# Generated by Django 5.1.1 on 2025-02-02 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_and_assigned_default_fk(apps,schema_editor):
    Checkout=apps.get_model('orders','Checkout')
    CustomUser=apps.get_model('users','CustomUser')
    default_user=CustomUser.objects.get(id=6)
    if default_user:
        Checkout.objects.filter(user__isnull=True).update(user=default_user.id)
class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_cartitem_cart_alter_checkout_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='orders.cart'),
        ),
    ]
