# Generated by Django 5.1.1 on 2025-02-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_checkout_user_alter_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
    ]
