# Generated by Django 5.1.1 on 2025-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
