# Generated by Django 5.1.1 on 2025-02-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_checkout_cart_data'),
        ('restaurant', '0015_alter_branch_address_delete_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordercart', to='restaurant.branch'),
        ),
    ]
