# Generated by Django 5.1.1 on 2025-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart_data',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
